/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HausCatalogue } from "./HausCatalogue";
export * as factories from "./factories";
export { HausCatalogue__factory } from "./factories/HausCatalogue__factory";
